### ISSUE TITLE
Fizz buzz problem

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#2] opened 2021-09-27 08:07 UTC
### Description

Write a Java Program to solve fizz buzz problem.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by Krupali-Tandel** [comment] 2021-09-30 15:47
@mbakrol  Assign me this issue

**Comment by AB-Jeet** [comment] 2021-09-30 19:20
Can you pls assign it to me ??

**Comment by ayushsaxena119** [comment] 2021-09-30 21:57
Assign this issue to me.

**Comment by AB-Jeet** [comment] 2021-10-01 01:28
Thanks for assigning me.

**Comment by prahasR** [comment] 2021-10-01 11:14
Hi @mbakrol, if the problem is open now, I am ready to contribute , please assign

**Comment by Niyati3031** [comment] 2021-10-02 01:31
Can you please assign this to me @mbakrol its my first time with github please help me to contribute

**Comment by pavitrapati** [comment] 2021-10-02 08:58
I would like to work on this issue with utmost sincerity. Please assign this issue to me.
@mbakrol

**Closed** 2021-10-03 11:01 UTC
Labels: HactoberFest
